server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8838
spring:
  datasource:
    username: pp
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/campus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
aliyun:
  oss:
    endpoint: oss-cn-hangzhou-internal.aliyuncs.com # oss内网域名
    accessKeyId: LTAI5tPjHuBGM58KU9fJWPhi # 访问身份验证中用到用户标识
    accessKeySecret: hqXyENIgd7iM0AoiDMm7kkShzhxIT8 # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: nicecampus # oss的存储空间
    baseUrl: https://nicecampus.oss-cn-hangzhou.aliyuncs.com/