server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8080
spring:
  thymeleaf:
    cache: false
  datasource:
    username: pp
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.203.154:3306/campus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml #指定mapper.xml路径
  global-config:
    db-config:
      id-type: auto #全局默认主键类型设置为自增
  configuration:
    auto-mapping-behavior: partial #只对非嵌套的 resultMap 进行自动映射
    map-underscore-to-camel-case: true #开启自动驼峰命名规则映射
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tPjHuBGM58KU9fJWPhi # 访问身份验证中用到用户标识
    accessKeySecret: hqXyENIgd7iM0AoiDMm7kkShzhxIT8 # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: macrosos # oss的存储空间
    baseUrl: https://macrosos.oss-cn-beijing.aliyuncs.com/
    policy:
      expire: 300 # 签名有效期(S)
      maxSize: 10 # 上传文件大小(M)
      callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: niceCampus/images/ # 上传文件夹路径前缀